AutoComplete/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('search/', include("Search.urls")),
    path('SearchView/', include("SearchView.urls")),

]

Search/urls.py
from django.conf.urls import url
from . import views
app_name = "search_keyword"
urlpatterns = [
    url(r'^addData/$', views.settings, name="settings"),
    url(r'^', views.search, name="search"),

]

SearchView/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name="search.html"), name="search")
    ]

Search/models.py
from django.db import models

# Create your models here.
class WordsData(models.Model):
    word = models.CharField(max_length=100)
    word_rank = models.IntegerField(max_length=20)


SearchView/models.py
from django.db import models

# Create your models here.

Search/views.py
from django.shortcuts import render
from django.http import HttpResponse, JsonResponse
from . import models

word = ""
def settings(request):
    """This function reads the TSV file, parse it and upload it to the MONGO DB"""
    file = open("word_search.tsv")
    array = []
    for f in file:
        temp = f.strip()
        array.append(temp.split('\t')) #Since TSV stands for Tab Seperated VALUES, we are seperating each data with respect to \t
    for data in array:
        obj = models.WordsData()
        obj.word = data[0]
        obj.word_rank = data[1]
        obj.save()
    return HttpResponse("<h3>TSV Data Successfully uploaded in the database</h3>")

def sorter(x):
    return len(x.word) #Key method to sort the array accordig to string length

def search(request):
    """This function processes the GET request search/?word= and returns a JSON array of 25 most relevent words """
    keyword = request.GET["word"]
    word = keyword
    data = models.WordsData.objects.filter(word__icontains=keyword).order_by("-word_rank")
    #The above ORM query selects data that matches  the keyword and orders it by word usage in descending order
    #The above ORM query confirms the first constrait, i.e., matches can occur anywhere in the string
    result = list(data)
    if len(result) > 25:
        max_length = 25
    else:
        max_length = len(result)
    """Since the data are in descending order in terms of usage and we require maximum of only 25 most common words, 
    we eliminate all words except the first 25 words"""
    temp_result = []
    checked = []
    i = 0
    while i < max_length:
        if keyword == result[i].word[0:len(keyword)]:
            """according to constraint given, matches at the start of the word should rank higher"""
            temp_result.append(result[i])
            checked.append(i)
        i += 1
    i = 0
    while i < max_length:
        if i in checked:
            i += 1
            continue
        else:
            temp_result.append(result[i])
            i += 1
    """The above code inserts all the words that matches  at the start in the list first"""
    final = sorted(temp_result, key=sorter)
    """The above code sorts the list according to the length of the word, 3rd constraint"""
    last = []
    for f in final:
        last.append(f.word)
    return JsonResponse({'context':last})

SearchView/views.py
from django.shortcuts import render

# Create your views here.

SearchView/templates/Header/header.html
<!DOCTYPE html>
<html>
<head>
    {% include "includes/bootstrap.html" %}
<title>Search</title>
</head>
<body>

{% block content %}
{% endblock %}
</body>
</html>

SearchView/templates/includes/bootstrap.html
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>

{% endblock %}

SearchView/templates/search.html
{% extends 'Header/header.html' %}

{% block content %}
<div class="container">
    <br>
    <div class="well">
        <h4><strong>Search Word</strong></h4>
        <p>Please enter the keywords in the input field , the webpage will make an Ajax GET request to the /search/?word=
        and dynamically show the values. The Ajax request takes a little bit of time since the database consists of 3Lakh +
            informations. The use of Mongo Db allows us to process such huge data. If you change the word in the input
        please wait for the </p>
    </div>
    <form>
        <div class="form-group">
            <input type="text" class="form-control" id="input">
        </div>
    </form>
    <ul id="autocomplete" class="list-group">
        <li class="list-group-item" id="loading" style="display:none;"><strong>LOADING...</strong></li>
    </ul>
</div>
<script>
    $(document).ready(function(event)
    {
        $(document).ajaxStart(function (){
            $("#loading").show();
                });
        $(document).ajaxComplete(function () {
                $("#loading").hide();
                });
        $("#input").keyup(function()
        {
            keyword = $("#input").val();
            $.ajax({
            type: "GET",
            url: "{% url 'search_keyword:search' %}",
            data: {'word':keyword},
            data_type: 'json',
            success: function(response)
            {
                data = response['context'];
                var i = 0;
                var html = ""
                for (i = 0; i < data.length; i++)
                {
                    html = html + "<li class='list-group-item'>" + data[i] + "</li>";
                }
                $("#autocomplete").html(html);
            },
            error: function(rs, e)
            {
                consol.log(rs.responseText);
            }
            });
        });
    });

</script>
{% endblock %}